### PR TITLE
Fixing the shortened url problem so that it now expands and opens correct

### PR DESCRIPTION
**Pull request by nloadholtes**
Hi, I changed the regex that looks at shortened URLs. This should strip off any non-alphanumeric chars and allow both the tab opener and the link expander to work with the URLs.

### CODE REVIEW

**Comment by SRabbelier** [comment]
Nice! Does this solve the (http://example.com/foo) -> http://example.com/foo) problem? When will this be making its way into a Silver Bird near me?

**Comment by nloadholtes** [comment]
Good question! This patch focuses on the trailing end of the URL, so that things like ",:;)]_= will get chopped off. It doesn't look at the start of the URL, so I'm not sure if it will catch the open ( at the beginning.

**Comment by nloadholtes** [comment]
Also, if you want to play with this patch, you can pull https://github.com/nloadholtes/silver_bird/tree/contributions That's the branch where I sent the request from.

**Comment by SRabbelier** [comment]
The problem I was having _is_ the end of the url, Silver Bird currently things that the ) or " is part of the url :).

**Comment by nloadholtes** [comment]
Oh, then this patch should work great! I'm having the same issue, Bruce Campbell ( @GroovyBruce) posts a lot of pictures encased in quotes and parentheses, and this patch works great with those. It even handles the hover feature (so you can see what the link points to without having to click on the link).

**Comment by SRabbelier** [comment]
Great! Looking forward to the next release :)

**Comment by kurtextrem** [comment]
Hey, it seems Cezarsa is inactive for months now... Maybe we could fork Silver Bird (maybe rename it) and update it? :D

**Comment by nloadholtes** [comment]
One thing I'm doing right now is I'm running the code by pointing Chrome to my checked out code directory, and I plugged in my own secret app keys into lib/secret.js. That way I can run the code in Chrome while I wait for the pull request to be accepted/rejected. Doing this allows me to test the code under normal usage.

**Comment by kurtextrem** [comment]
I know, I'm a developer. But maybe Silver Bird User want to get in touch with fancy changes too?

**Comment by nloadholtes** [comment]
I also added in changeset d4d27d4 to address the problem raised in issue #347 (the angle brackets being displayed as &gt; and &lt; )

**Comment by nloadholtes** [comment]
I am withdrawing this pull request, with all of the recent changes it seems like this code isn't working any more.

**Pull request closed without merging**
